name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Install Linux dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            wget \
            curl \
            autoconf \
            automake \
            libtool \
            pkg-config \
            build-essential \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libltdl-dev \
            libsqlite3-dev \
            cmake \
            ninja-build \
            ccache


      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython


      # First run to let buildozer create SDK folders
      - name: Bootstrap Buildozer
        run: |
          buildozer android clean || true


      # Install Android build tools (AIDL fix)
      - name: Install Android build-tools
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg

          SDK=~/.buildozer/android/platform/android-sdk
          CMD=$SDK/cmdline-tools/latest/bin/sdkmanager

          yes | $CMD --licenses || true
          $CMD "platform-tools"
          $CMD "platforms;android-31"
          $CMD "build-tools;33.0.2"


      - name: Build APK
        run: |
          buildozer -v android debug


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
