name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip git zip unzip openjdk-17-jdk

      - name: Install Python tools
        run: |
          pip3 install buildozer cython

      - name: Setup Android SDK for Buildozer
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform

          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-*.zip

          mkdir -p android-sdk/cmdline-tools
          mv cmdline-tools android-sdk/cmdline-tools/latest

          export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH

          yes | sdkmanager --licenses
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"

          mkdir -p $ANDROID_HOME/tools/bin
          ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AladdinQuantAI-APK
          path: bin/*.apk
